import { getAccessToken } from './firebaseAuth';

export interface DriveFileResult {
  id: string;
  name: string;
  webViewLink: string;
}

export async function uploadInvoiceToDrive(
  invoiceNumber: string,
  htmlContent: string
): Promise<DriveFileResult> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google Drive authorization required. Please sign in with Google.');
  }

  const fileName = `Invoice_${invoiceNumber}.html`;
  const metadata = {
    name: fileName,
    mimeType: 'text/html',
    description: `GST Tax Invoice generated by ABC Paper & Stationery for ${invoiceNumber}`,
  };

  const form = new FormData();
  form.append(
    'metadata',
    new Blob([JSON.stringify(metadata)], { type: 'application/json' })
  );
  form.append('file', new Blob([htmlContent], { type: 'text/html' }));

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: form,
    }
  );

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || 'Failed to upload invoice to Google Drive');
  }

  return response.json();
}

export async function uploadReportToDrive(
  reportTitle: string,
  csvOrTextContent: string,
  mimeType: string = 'text/csv'
): Promise<DriveFileResult> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google Drive authorization required. Please sign in with Google.');
  }

  const extension = mimeType === 'text/csv' ? '.csv' : '.txt';
  const fileName = `${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}${extension}`;
  const metadata = {
    name: fileName,
    mimeType,
    description: `Report exported from ABC Paper & Stationery shop management.`,
  };

  const form = new FormData();
  form.append(
    'metadata',
    new Blob([JSON.stringify(metadata)], { type: 'application/json' })
  );
  form.append('file', new Blob([csvOrTextContent], { type: mimeType }));

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: form,
    }
  );

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || 'Failed to upload report to Google Drive');
  }

  return response.json();
}
